tb <-read.csv(file.choose(), header=T)
attach(tb)
head(tb)
monthCheeseTS <- ts(tb$Cheese,frequency=12,start=c(1994,1))
autoplot(monthCheeseTS)
myData2 <-read.csv(file.choose(), header=T)
attach(myData2)
head(myData2)
YCheeseTS <- ts(myData2$CheeseY,frequency=1,start=c(1994,1))
autoplot(YCheeseTS)
mod1 <- rwf(YCheeseTS,h=5, drift=TRUE)
summary(mod1)
autoplot(mod1)
checkresiduals(mod1)
mod2<-holt(YCheeseTS,h=5)
summary(mod2)
autoplot(mod2)
checkresiduals(mod2)
mod3<- auto.arima(monthCheeseTS)
summary(mod3)
checkresiduals(mod3)
autoplot(forecast(mod3, h=60))
mod4<- ets(monthCheeseTS)
summary(mod4)
checkresiduals(mod4)
autoplot(forecast(mod4, h=60))
tb